version: '3.1'

services:
  app:
    container_name: recon_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - mongo
    environment:
      # CHANGE PASSWORD !!!
      DYNACONF_MONGO_INITDB_ROOT_USERNAME: 'root'
      DYNACONF_MONGO_INITDB_ROOT_PASSWORD: 'toor'
      DYNACONF_MONGO_DB_ADDRESS: 'mongo'
    volumes:
      - "./mongodb:/root"
    networks:
      - backend
  mongo:
    container_name: recon_mongo
    image: mongo
    restart: always
    
    environment:
      # CHANGE PASSWORD !!!
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    networks:
      - backend
networks:
  backend:
